set nocompatible              " be iMproved, required
filetype off                  " required during Vundle calls

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'

" Filetype integrations
Plugin 'ledger/vim-ledger'

" Navigation
Plugin 'scrooloose/nerdtree'

" Git
Plugin 'tpope/vim-fugitive'
Plugin 'airblade/vim-gitgutter'
Plugin 'Xuyuanp/nerdtree-git-plugin'

" Autocompletion
Plugin 'valloric/youcompleteme'

" Syntax checking
Plugin 'scrooloose/syntastic'

" Themes
Plugin 'altercation/vim-colors-solarized'

" Display Whitespace
Plugin 'ntpeters/vim-better-whitespace'

call vundle#end()

" Required:
filetype plugin indent on

syntax enable
set background=dark
colorscheme solarized
" allow backspacing over everything in insert mode
set backspace=indent,eol,start

let NERDTreeShowHidden=1

" Autocompletion on
set omnifunc=syntaxcomplete#Complete

" Vim internal tab-completion
set wildmenu
set wildmode=list:longest

set nobackup		" do not keep a backup file, use versions instead
set history=50		" keep 50 lines of command line history
set incsearch		" do incremental searching

" Don't use Ex mode, use Q for formatting
map Q gq

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" Make selections go into the system clipboard
set clipboard=unnamedplus

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif

" Global tab settings
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab
